/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/alliances/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Rank alliances by total power
         * @description An hourly roll-up ranking alliances by total power, globally or within one State. Counts and totals only; it names no member.
         */
        get: operations["allianceLeaderboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/alliances/recruiting": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List alliances taking applications
         * @description Alliances open to applications that still have a seat free, filtered by State, language and joining requirements.
         */
        get: operations["allianceRecruiting"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/alliances/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search alliances by tag or name
         * @description Free-text search over alliance tags and names, with a per-State member breakdown on each hit. Counts against the search window.
         */
        get: operations["searchAlliances"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/alliances/{aid}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch one alliance and its roster
         * @description The alliance record and every member the atlas has mapped to it. A keyed read, not a scan.
         */
        get: operations["getAllianceMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/players/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search players by name or Chief ID
         * @description Free-text search over player names, with exact Chief ID and internal uid matches merged in front of the name page. Counts against the search window.
         */
        get: operations["searchPlayers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/players/{uid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch one player by internal uid
         * @description The current snapshot for one player, keyed on the atlas's own uid rather than the Chief ID a player sees.
         */
        get: operations["getPlayer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            details: {
                [key: string]: unknown;
            };
            error: string;
            message: string;
            /** Format: date-time */
            retryAfter: string;
            /** Format: date-time */
            timestamp: string;
        };
    };
    responses: {
        /** @description INVALID_API_KEY — The key is unknown, revoked, or its owning account has been deleted. */
        Unauthorized: {
            headers: {
                /** @description The account's read allowance for the rolling thirty-day window. */
                "X-Quota-Limit"?: string;
                /** @description Reads left in that window. */
                "X-Quota-Remaining"?: string;
                /** @description Unix seconds at which the oldest read in the window ages out. */
                "X-Quota-Reset"?: string;
                /** @description The account's search allowance for the rolling twenty-four-hour window. */
                "X-Search-Limit"?: string;
                /** @description Searches left in that window. */
                "X-Search-Remaining"?: string;
                /** @description Unix seconds at which the oldest search in the window ages out. */
                "X-Search-Reset"?: string;
                /** @description The account's burst allowance for the short window. */
                "X-RateLimit-Limit"?: string;
                /** @description Requests left in the burst window. */
                "X-RateLimit-Remaining"?: string;
                /** @description Unix seconds at which the burst window rolls. */
                "X-RateLimit-Reset"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description ENDPOINT_NOT_ALLOWED — The route is not on the developer surface. Presenting a key on a route off the surface is refused rather than served, so do not send a key to endpoints this document does not list. */
        Forbidden: {
            headers: {
                /** @description The account's read allowance for the rolling thirty-day window. */
                "X-Quota-Limit"?: string;
                /** @description Reads left in that window. */
                "X-Quota-Remaining"?: string;
                /** @description Unix seconds at which the oldest read in the window ages out. */
                "X-Quota-Reset"?: string;
                /** @description The account's search allowance for the rolling twenty-four-hour window. */
                "X-Search-Limit"?: string;
                /** @description Searches left in that window. */
                "X-Search-Remaining"?: string;
                /** @description Unix seconds at which the oldest search in the window ages out. */
                "X-Search-Reset"?: string;
                /** @description The account's burst allowance for the short window. */
                "X-RateLimit-Limit"?: string;
                /** @description Requests left in the burst window. */
                "X-RateLimit-Remaining"?: string;
                /** @description Unix seconds at which the burst window rolls. */
                "X-RateLimit-Reset"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description QUOTA_EXCEEDED — The account's rolling thirty-day read quota is spent. `X-Quota-Remaining` reads zero; `X-Search-Remaining` stays honest. SEARCH_QUOTA_EXCEEDED — The account's rolling twenty-four-hour search quota is spent. `X-Search-Remaining` reads zero; `X-Quota-Remaining` stays honest. Only the two search routes count against it. RATE_LIMIT_EXCEEDED — The account's short burst window is full. `X-RateLimit-Remaining` reads zero. This is a per-second-scale ceiling and clears on its own; neither quota window has been touched. */
        TooManyRequests: {
            headers: {
                /** @description The account's read allowance for the rolling thirty-day window. */
                "X-Quota-Limit"?: string;
                /** @description Reads left in that window. */
                "X-Quota-Remaining"?: string;
                /** @description Unix seconds at which the oldest read in the window ages out. */
                "X-Quota-Reset"?: string;
                /** @description The account's search allowance for the rolling twenty-four-hour window. */
                "X-Search-Limit"?: string;
                /** @description Searches left in that window. */
                "X-Search-Remaining"?: string;
                /** @description Unix seconds at which the oldest search in the window ages out. */
                "X-Search-Reset"?: string;
                /** @description The account's burst allowance for the short window. */
                "X-RateLimit-Limit"?: string;
                /** @description Requests left in the burst window. */
                "X-RateLimit-Remaining"?: string;
                /** @description Unix seconds at which the burst window rolls. */
                "X-RateLimit-Reset"?: string;
                /** @description Seconds to wait before retrying. Sent on every 429, and specific to the window that denied. */
                "Retry-After"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    allianceLeaderboard: {
        parameters: {
            query?: {
                /**
                 * @description Rank within this State only. Omit for the global ranking.
                 * @example 165
                 */
                kid?: number;
                /**
                 * @description How many rows to return.
                 * @example 25
                 */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The census read. */
            200: {
                headers: {
                    /** @description The account's read allowance for the rolling thirty-day window. */
                    "X-Quota-Limit"?: string;
                    /** @description Reads left in that window. */
                    "X-Quota-Remaining"?: string;
                    /** @description Unix seconds at which the oldest read in the window ages out. */
                    "X-Quota-Reset"?: string;
                    /** @description The account's search allowance for the rolling twenty-four-hour window. */
                    "X-Search-Limit"?: string;
                    /** @description Searches left in that window. */
                    "X-Search-Remaining"?: string;
                    /** @description Unix seconds at which the oldest search in the window ages out. */
                    "X-Search-Reset"?: string;
                    /** @description The account's burst allowance for the short window. */
                    "X-RateLimit-Limit"?: string;
                    /** @description Requests left in the burst window. */
                    "X-RateLimit-Remaining"?: string;
                    /** @description Unix seconds at which the burst window rolls. */
                    "X-RateLimit-Reset"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        entries: {
                            abbr: string;
                            /** Format: int64 */
                            aid: number;
                            /** Format: int32 */
                            joinMinLevel: number;
                            /** Format: int64 */
                            joinMinPower: number;
                            /** Format: int32 */
                            kid: number;
                            kingdomName: string;
                            /** Format: int64 */
                            maxPower: number;
                            /** Format: int64 */
                            medianPower: number;
                            /** Format: int32 */
                            memberMax: number;
                            /** Format: int32 */
                            members: number;
                            name: string;
                            publicRecruit: boolean;
                            /** @enum {string} */
                            recordSource: "SERVER" | "DERIVED";
                            /** Format: date-time */
                            recordedAt: string;
                            /** Format: int64 */
                            totalPower: number;
                        }[];
                        /** Format: int32 */
                        kid: number;
                        /** Format: date-time */
                        recordedAt: string;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    allianceRecruiting: {
        parameters: {
            query?: {
                /**
                 * @description Restrict to one State.
                 * @example 165
                 */
                kid?: number;
                /**
                 * @description The alliance's declared language, in the game's own vocabulary.
                 * @example 1
                 */
                language?: number;
                /**
                 * @description Exclude alliances whose joining level requirement is above this.
                 * @example 25
                 */
                minLevel?: number;
                /**
                 * @description Exclude alliances whose joining power requirement is above this.
                 * @example 1000000
                 */
                minPower?: number;
                /**
                 * @description Only alliances whose own total power is at least this.
                 * @example 1000000
                 */
                powerMin?: number;
                /**
                 * @description Only alliances whose own total power is at most this.
                 * @example 9000000000
                 */
                powerMax?: number;
                /**
                 * @description Page size.
                 * @example 25
                 */
                limit?: number;
                /**
                 * @description How many rows to skip.
                 * @example 0
                 */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The census read. */
            200: {
                headers: {
                    /** @description The account's read allowance for the rolling thirty-day window. */
                    "X-Quota-Limit"?: string;
                    /** @description Reads left in that window. */
                    "X-Quota-Remaining"?: string;
                    /** @description Unix seconds at which the oldest read in the window ages out. */
                    "X-Quota-Reset"?: string;
                    /** @description The account's search allowance for the rolling twenty-four-hour window. */
                    "X-Search-Limit"?: string;
                    /** @description Searches left in that window. */
                    "X-Search-Remaining"?: string;
                    /** @description Unix seconds at which the oldest search in the window ages out. */
                    "X-Search-Reset"?: string;
                    /** @description The account's burst allowance for the short window. */
                    "X-RateLimit-Limit"?: string;
                    /** @description Requests left in the burst window. */
                    "X-RateLimit-Remaining"?: string;
                    /** @description Unix seconds at which the burst window rolls. */
                    "X-RateLimit-Reset"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        entries: {
                            abbr: string;
                            /** Format: int64 */
                            aid: number;
                            /** Format: int32 */
                            joinMinLevel: number;
                            /** Format: int64 */
                            joinMinPower: number;
                            /** Format: int32 */
                            kid: number;
                            kingdomName: string;
                            /** Format: int32 */
                            language: number;
                            /** Format: int32 */
                            memberMax: number;
                            /** Format: int32 */
                            members: number;
                            name: string;
                            /** Format: int64 */
                            power: number;
                            /** Format: date-time */
                            powerReadAt: string;
                            publicRecruit: boolean;
                            /** Format: date-time */
                            recordReadAt: string;
                            /** @enum {string} */
                            recordSource: "SERVER" | "DERIVED";
                        }[];
                        /** Format: int32 */
                        limit: number;
                        /** Format: int32 */
                        offset: number;
                        /** Format: date-time */
                        recordsReadAt: string;
                        /** Format: int32 */
                        total: number;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    searchAlliances: {
        parameters: {
            query: {
                /**
                 * @description An alliance tag or name fragment.
                 * @example EVL
                 */
                tag: string;
                /**
                 * @description Restrict the search to these State ids.
                 * @example 165
                 */
                kingdomIds?: number[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The census read. */
            200: {
                headers: {
                    /** @description The account's read allowance for the rolling thirty-day window. */
                    "X-Quota-Limit"?: string;
                    /** @description Reads left in that window. */
                    "X-Quota-Remaining"?: string;
                    /** @description Unix seconds at which the oldest read in the window ages out. */
                    "X-Quota-Reset"?: string;
                    /** @description The account's search allowance for the rolling twenty-four-hour window. */
                    "X-Search-Limit"?: string;
                    /** @description Searches left in that window. */
                    "X-Search-Remaining"?: string;
                    /** @description Unix seconds at which the oldest search in the window ages out. */
                    "X-Search-Reset"?: string;
                    /** @description The account's burst allowance for the short window. */
                    "X-RateLimit-Limit"?: string;
                    /** @description Requests left in the burst window. */
                    "X-RateLimit-Remaining"?: string;
                    /** @description Unix seconds at which the burst window rolls. */
                    "X-RateLimit-Reset"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        alliances: {
                            abbr: string;
                            /** Format: int64 */
                            aid: number;
                            /** Format: int32 */
                            homeKid: number;
                            homeKingdomName: string;
                            kingdoms: {
                                /** Format: int32 */
                                kid: number;
                                kingdomName: string;
                                /** Format: int32 */
                                memberCount: number;
                            }[];
                            /** Format: int64 */
                            totalMembers: number;
                        }[];
                        /** @enum {string} */
                        viewerTier: "ANONYMOUS" | "FREE" | "PASS" | "DEVELOPER";
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    getAllianceMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The alliance id.
                 * @example 1000015
                 */
                aid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The census read. */
            200: {
                headers: {
                    /** @description The account's read allowance for the rolling thirty-day window. */
                    "X-Quota-Limit"?: string;
                    /** @description Reads left in that window. */
                    "X-Quota-Remaining"?: string;
                    /** @description Unix seconds at which the oldest read in the window ages out. */
                    "X-Quota-Reset"?: string;
                    /** @description The account's search allowance for the rolling twenty-four-hour window. */
                    "X-Search-Limit"?: string;
                    /** @description Searches left in that window. */
                    "X-Search-Remaining"?: string;
                    /** @description Unix seconds at which the oldest search in the window ages out. */
                    "X-Search-Reset"?: string;
                    /** @description The account's burst allowance for the short window. */
                    "X-RateLimit-Limit"?: string;
                    /** @description Requests left in the burst window. */
                    "X-RateLimit-Remaining"?: string;
                    /** @description Unix seconds at which the burst window rolls. */
                    "X-RateLimit-Reset"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        abbr: string;
                        /** Format: int64 */
                        aid: number;
                        /** Format: int32 */
                        derivedMemberCount: number;
                        /** Format: date-time */
                        derivedRecordedAt: string;
                        /** Format: int64 */
                        derivedTotalPower: number;
                        /** Format: int32 */
                        homeKid: number;
                        /** Format: int32 */
                        honorLevel: number;
                        /** Format: int32 */
                        joinMinLevel: number;
                        /** Format: int64 */
                        joinMinPower: number;
                        /** Format: int32 */
                        language: number;
                        leaderName: string;
                        /** Format: int64 */
                        leaderUid: number;
                        /** Format: int32 */
                        lv: number;
                        manifesto: string;
                        /** Format: int32 */
                        memberCount: number;
                        /** Format: int32 */
                        memberMax: number;
                        members: {
                            abbr: string;
                            /** Format: int32 */
                            kid: number;
                            kingdom_name: string;
                            /** Format: int32 */
                            lv: number;
                            nick_name: string;
                            /** Format: int32 */
                            office: number;
                            /** Format: int64 */
                            uid: number;
                            /** Format: int32 */
                            x: number;
                            /** Format: int32 */
                            y: number;
                        }[];
                        name: string;
                        notice: string;
                        noticePresent: boolean;
                        /** Format: date-time */
                        noticeTime: string;
                        /** Format: int32 */
                        powerRank: number;
                        publicRecruit: boolean;
                        /** Format: int32 */
                        rankedAlliances: number;
                        /** Format: date-time */
                        recordMissingSince: string;
                        /** Format: date-time */
                        recordReadAt: string;
                        /** @enum {string} */
                        recordSource: "SERVER" | "DERIVED";
                        /** Format: int64 */
                        serverPower: number;
                        /** Format: int32 */
                        serverPowerRank: number;
                        /** @enum {string} */
                        viewerTier: "ANONYMOUS" | "FREE" | "PASS" | "DEVELOPER";
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    searchPlayers: {
        parameters: {
            query: {
                /**
                 * @description A name fragment, a Chief ID, or an internal uid.
                 * @example LordFrost
                 */
                playerName: string;
                /**
                 * @description Restrict the search to these State ids. Repeat or comma-separate.
                 * @example 165
                 */
                kingdomIds?: number[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The census read. */
            200: {
                headers: {
                    /** @description The account's read allowance for the rolling thirty-day window. */
                    "X-Quota-Limit"?: string;
                    /** @description Reads left in that window. */
                    "X-Quota-Remaining"?: string;
                    /** @description Unix seconds at which the oldest read in the window ages out. */
                    "X-Quota-Reset"?: string;
                    /** @description The account's search allowance for the rolling twenty-four-hour window. */
                    "X-Search-Limit"?: string;
                    /** @description Searches left in that window. */
                    "X-Search-Remaining"?: string;
                    /** @description Unix seconds at which the oldest search in the window ages out. */
                    "X-Search-Reset"?: string;
                    /** @description The account's burst allowance for the short window. */
                    "X-RateLimit-Limit"?: string;
                    /** @description Requests left in the burst window. */
                    "X-RateLimit-Remaining"?: string;
                    /** @description Unix seconds at which the burst window rolls. */
                    "X-RateLimit-Reset"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        idOutcome: "MATCHED" | "UNMATCHED_INCOMPLETE" | "UNMATCHED_COMPLETE" | "NOT_AN_ID";
                        players: {
                            abbr: string;
                            /** Format: int64 */
                            aid: number;
                            /** Format: int64 */
                            current_power: number;
                            /** Format: int64 */
                            fid: number;
                            /** Format: int32 */
                            furnace_lv: number;
                            /** Format: int32 */
                            kid: number;
                            kingdom_name: string;
                            last_jump_pct: number;
                            /** Format: int32 */
                            lv: number;
                            nick_name: string;
                            /** Format: date-time */
                            observed_at: string;
                            /** Format: int32 */
                            stove_lv: number;
                            /** Format: int64 */
                            uid: number;
                            /** Format: int32 */
                            x: number;
                            /** Format: int32 */
                            y: number;
                        }[];
                        /** Format: int32 */
                        stateKid: number;
                        /** @enum {string} */
                        viewerTier: "ANONYMOUS" | "FREE" | "PASS" | "DEVELOPER";
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    getPlayer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The atlas's internal player id, as returned by the search routes.
                 * @example 400001
                 */
                uid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The census read. */
            200: {
                headers: {
                    /** @description The account's read allowance for the rolling thirty-day window. */
                    "X-Quota-Limit"?: string;
                    /** @description Reads left in that window. */
                    "X-Quota-Remaining"?: string;
                    /** @description Unix seconds at which the oldest read in the window ages out. */
                    "X-Quota-Reset"?: string;
                    /** @description The account's search allowance for the rolling twenty-four-hour window. */
                    "X-Search-Limit"?: string;
                    /** @description Searches left in that window. */
                    "X-Search-Remaining"?: string;
                    /** @description Unix seconds at which the oldest search in the window ages out. */
                    "X-Search-Reset"?: string;
                    /** @description The account's burst allowance for the short window. */
                    "X-RateLimit-Limit"?: string;
                    /** @description Requests left in the burst window. */
                    "X-RateLimit-Remaining"?: string;
                    /** @description Unix seconds at which the burst window rolls. */
                    "X-RateLimit-Reset"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        idOutcome: "MATCHED" | "UNMATCHED_INCOMPLETE" | "UNMATCHED_COMPLETE" | "NOT_AN_ID";
                        players: {
                            abbr: string;
                            /** Format: int64 */
                            aid: number;
                            /** Format: int64 */
                            current_power: number;
                            /** Format: int64 */
                            fid: number;
                            /** Format: int32 */
                            furnace_lv: number;
                            /** Format: int32 */
                            kid: number;
                            kingdom_name: string;
                            last_jump_pct: number;
                            /** Format: int32 */
                            lv: number;
                            nick_name: string;
                            /** Format: date-time */
                            observed_at: string;
                            /** Format: int32 */
                            stove_lv: number;
                            /** Format: int64 */
                            uid: number;
                            /** Format: int32 */
                            x: number;
                            /** Format: int32 */
                            y: number;
                        }[];
                        /** Format: int32 */
                        stateKid: number;
                        /** @enum {string} */
                        viewerTier: "ANONYMOUS" | "FREE" | "PASS" | "DEVELOPER";
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
        };
    };
}
